### ISSUE TITLE
Example not compiling

### ISSUE THREAD

**Issue by DavidBro07** [WebexSamples/webex-meetings-quick-start#1]
Hi! I've tried to run the example here, but I just can't make it work and havent found many information about the error online...

I tried running it with npm start and also with ./node_modules/.bin/parcel index.html and have the exact same result

The error is...

×  C:\...\node_modules\pkijs\src\CertificateChainValidationEngine.js: C:\...\node_modules\pkijs\src\CertificateChainValidationEngine.js: unknown Statement of type "ForOfStatement"
    at Emitter.Ep.explodeStatement (C:\...\node_modules\regenerator-transform\lib\emit.js:587:13)
    at C:\...\node_modules\regenerator-transform\lib\emit.js:323:12
    at Array.forEach (<anonymous>)
    at Emitter.Ep.explodeStatement (C:\...\node_modules\regenerator-transform\lib\emit.js:322:22)
    at Emitter.Ep.explodeStatement (C:\...\node_modules\regenerator-transform\lib\emit.js:510:12)
    at C:\...\node_modules\regenerator-transform\lib\emit.js:323:12
    at Array.forEach (<anonymous>)
    at Emitter.Ep.explodeStatement (C:\...\node_modules\regenerator-transform\lib\emit.js:322:22)
    at Emitter.Ep.explode (C:\...\node_modules\regenerator-transform\lib\emit.js:280:40)
    at PluginPass.<anonymous> (C:\...\node_modules\regenerator-transform\lib\visit.js:111:17)

Hope anyone can help me, I tried the same example six months ago and everything work fine, I didn't know what've changed

**Comment by lifekent** [comment]
Same issue for me. Any updates on that?

**Comment by mwegman** [comment]
Try running the command `nvm install lts/dubnium` before running `npm install` and `npm start`

**Comment by lifekent** [comment]
> Try running the command `nvm install lts/dubnium` before running `npm install` and `npm start`
I've managed to get it running. Thank you

**Comment by owaishussain** [comment]
> > Try running the command `nvm install lts/dubnium` before running `npm install` and `npm start`
> 
> I've managed to get it running. Thank you

how?
